### ISSUE TITLE
Symmetry search has problems on 3x3x3 supercell

### ISSUE THREAD

**Issue by jochym** [ttadano/alamode#6]
It seems that for the odd multiplicity of the supercell (in my case 3x3x3) the symmetry finder finds only tiny fraction of the symmetry operations (1536  for 2x2x2 vs.  48 for 3x3x3) which makes the fitting procedure fail. I can provide a test-case data for this issue. 
- What may be the reason of this behaviour? 
- Is this "by design" i.e. is this a limitation of  the symmetry search algorithm used?
I have checked with spglib symmetry finder that the actual symmetry of the cell is not changed.

The problematic case is a Fm-3m crystal with two atom base:

 1.8897259890 # factor 
 0.0000000000   3.2800896279   3.2800896279
 3.2800896279   0.0000000000   3.2800896279
 3.2800896279   3.2800896279   0.0000000000 # cell matrix

Atom A: 0, 0, 0 
Atom B: 1/2, 1/2, 1/2

**Comment by ttadano** [comment]
Probably, the problem occurred due to the insufficient number of significant figures in the fractional coordinates of atoms in the supercell. It's recommended to use 15 digit to represent a fractional number like 1/3 ~ 0.333333333333333. This should solve the issue.
Instead of increasing the number of figures, you may be able to solve the problem by loosening the tolerance by the TOLERANCE-tag (default: 1.0e-6). 

The spglib is designed very well and works robustly, so we are thinking of replacing our own symmetry routine with the spglib in a forthcoming update.

**Comment by jochym** [comment]
Unfortunately the TOLERANCE did not fix it (I went as far as 1e-5). Furthermore if I increase the same unit cell to 4x4x4 (so even multiplicity) it works again. So this seems to be indeed connected with odd/even multiplicity. Any way I can help in fixing this?

**Comment by ttadano** [comment]
With the following input, the code successfully detected 1296 (= 48*27) space group operations. Could you try with it?

```
&general
 PREFIX = test
 MODE = suggest
 NAT = 54; NKD = 2; KD = A B
/

&interaction
 NORDER = 1
/

&cutoff
 *-* N
/

&cell
1.8897259890 # factor
 0.0000000000 3.2800896279 3.2800896279
 3.2800896279 0.0000000000 3.2800896279
 3.2800896279 3.2800896279 0.0000000000 # cell matrix
/
&position
  1    0.000000000000000    0.000000000000000    0.000000000000000
  1    0.000000000000000    0.000000000000000    0.333333333333333
  1    0.000000000000000    0.000000000000000    0.666666666666667
  1    0.000000000000000    0.333333333333333    0.000000000000000
  1    0.000000000000000    0.333333333333333    0.333333333333333
  1    0.000000000000000    0.333333333333333    0.666666666666667
  1    0.000000000000000    0.666666666666667    0.000000000000000
  1    0.000000000000000    0.666666666666667    0.333333333333333
  1    0.000000000000000    0.666666666666667    0.666666666666667
  1    0.333333333333333    0.000000000000000    0.000000000000000
  1    0.333333333333333    0.000000000000000    0.333333333333333
  1    0.333333333333333    0.000000000000000    0.666666666666667
  1    0.333333333333333    0.333333333333333    0.000000000000000
  1    0.333333333333333    0.333333333333333    0.333333333333333
  1    0.333333333333333    0.333333333333333    0.666666666666667
  1    0.333333333333333    0.666666666666667    0.000000000000000
  1    0.333333333333333    0.666666666666667    0.333333333333333
  1    0.333333333333333    0.666666666666667    0.666666666666667
  1    0.666666666666667    0.000000000000000    0.000000000000000
  1    0.666666666666667    0.000000000000000    0.333333333333333
  1    0.666666666666667    0.000000000000000    0.666666666666667
  1    0.666666666666667    0.333333333333333    0.000000000000000
  1    0.666666666666667    0.333333333333333    0.333333333333333
  1    0.666666666666667    0.333333333333333    0.666666666666667
  1    0.666666666666667    0.666666666666667    0.000000000000000
  1    0.666666666666667    0.666666666666667    0.333333333333333
  1    0.666666666666667    0.666666666666667    0.666666666666667
  2    0.166666666666667    0.166666666666667    0.166666666666667
  2    0.166666666666667    0.166666666666667    0.500000000000000
  2    0.166666666666667    0.166666666666667    0.833333333333333
  2    0.166666666666667    0.500000000000000    0.166666666666667
  2    0.166666666666667    0.500000000000000    0.500000000000000
  2    0.166666666666667    0.500000000000000    0.833333333333333
  2    0.166666666666667    0.833333333333333    0.166666666666667
  2    0.166666666666667    0.833333333333333    0.500000000000000
  2    0.166666666666667    0.833333333333333    0.833333333333333
  2    0.500000000000000    0.166666666666667    0.166666666666667
  2    0.500000000000000    0.166666666666667    0.500000000000000
  2    0.500000000000000    0.166666666666667    0.833333333333333
  2    0.500000000000000    0.500000000000000    0.166666666666667
  2    0.500000000000000    0.500000000000000    0.500000000000000
  2    0.500000000000000    0.500000000000000    0.833333333333333
  2    0.500000000000000    0.833333333333333    0.166666666666667
  2    0.500000000000000    0.833333333333333    0.500000000000000
  2    0.500000000000000    0.833333333333333    0.833333333333333
  2    0.833333333333333    0.166666666666667    0.166666666666667
  2    0.833333333333333    0.166666666666667    0.500000000000000
  2    0.833333333333333    0.166666666666667    0.833333333333333
  2    0.833333333333333    0.500000000000000    0.166666666666667
  2    0.833333333333333    0.500000000000000    0.500000000000000
  2    0.833333333333333    0.500000000000000    0.833333333333333
  2    0.833333333333333    0.833333333333333    0.166666666666667
  2    0.833333333333333    0.833333333333333    0.500000000000000
  2    0.833333333333333    0.833333333333333    0.833333333333333
/
```

**Comment by jochym** [comment]
Thanks for your help. The above example is quite possible, but it is also quite different from my problematic case. The unit cell I cited:
```
&cell
    1.8897259890 # factor 
    0.0000000000   3.2800896279   3.2800896279
    3.2800896279   0.0000000000   3.2800896279
    3.2800896279   3.2800896279   0.0000000000 # cell matrix
/
```
 is from the `phonon.in` file and corresponds to a FCC unit cell. 
The problematic `fit.in` file is as follows. Please, try if you can reproduce the problem. It is quite possible that I am doing something wrong:
```
&general
  PREFIX = example
  MODE = fitting 
  NAT = 216
  NKD = 2
  KD = A B
  TOLERANCE = 1.e-5
  PRINTSYM = 1
/

&interaction
  NORDER = 1  # 1: harmonic, 2: cubic, ..
/

&cell
    1.8897259890 # factor 
   19.6805377673   0.0000000000   0.0000000000
    0.0000000000  19.6805377673   0.0000000000
   -0.0000000000   0.0000000000  19.6805377673 # cell matrix
/

&cutoff 
*-* None
/

&position
1  0.8333333333333333  0.8333333333333333  0.6666666666666667
1  0.6666666666666667  0.0000000000000000  0.6666666666666667
1  0.6666666666666667  0.1666666666666667  0.8333333333333333
1  0.8333333333333333  0.0000000000000000  0.8333333333333333
1  0.5000000000000000  0.1666666666666667  0.6666666666666667
1  0.5000000000000000  0.0000000000000000  0.8333333333333333
1  0.3333333333333333  0.1666666666666667  0.8333333333333333
1  0.3333333333333333  0.0000000000000000  0.6666666666666667
1  0.8333333333333333  0.1666666666666667  0.6666666666666667
1  0.5000000000000000  0.1666666666666667  0.3333333333333333
1  0.5000000000000000  0.0000000000000000  0.5000000000000000
1  0.3333333333333333  0.1666666666666667  0.5000000000000000
1  0.3333333333333333  0.0000000000000000  0.3333333333333333
1  0.6666666666666667  0.3333333333333333  0.0000000000000000
1  0.6666666666666667  0.5000000000000000  0.1666666666666667
1  0.8333333333333333  0.3333333333333333  0.1666666666666667
1  0.5000000000000000  0.1666666666666667  0.0000000000000000
1  0.5000000000000000  0.0000000000000000  0.1666666666666667
1  0.3333333333333333  0.1666666666666667  0.1666666666666667
1  0.3333333333333333  0.0000000000000000  0.0000000000000000
1  0.8333333333333333  0.5000000000000000  0.0000000000000000
1  0.5000000000000000  0.6666666666666667  0.8333333333333333
1  0.1666666666666667  0.6666666666666667  0.8333333333333333
1  0.0000000000000000  0.8333333333333333  0.8333333333333333
1  0.0000000000000000  0.6666666666666667  0.6666666666666667
1  0.6666666666666667  0.3333333333333333  0.3333333333333333
1  0.6666666666666667  0.5000000000000000  0.5000000000000000
1  0.8333333333333333  0.3333333333333333  0.5000000000000000
1  0.3333333333333333  0.3333333333333333  0.0000000000000000
1  0.1666666666666667  0.8333333333333333  0.3333333333333333
1  0.3333333333333333  0.5000000000000000  0.1666666666666667
1  0.5000000000000000  0.5000000000000000  0.0000000000000000
1  0.3333333333333333  0.8333333333333333  0.8333333333333333
1  0.3333333333333333  0.6666666666666667  0.6666666666666667
1  0.5000000000000000  0.8333333333333333  0.3333333333333333
1  0.5000000000000000  0.6666666666666667  0.5000000000000000
1  0.3333333333333333  0.8333333333333333  0.5000000000000000
1  0.3333333333333333  0.6666666666666667  0.3333333333333333
1  0.6666666666666667  0.0000000000000000  0.0000000000000000
1  0.6666666666666667  0.1666666666666667  0.1666666666666667
1  0.8333333333333333  0.0000000000000000  0.1666666666666667
1  0.8333333333333333  0.1666666666666667  0.0000000000000000
1  0.5000000000000000  0.8333333333333333  0.0000000000000000
1  0.5000000000000000  0.6666666666666667  0.1666666666666667
1  0.3333333333333333  0.8333333333333333  0.1666666666666667
1  0.3333333333333333  0.6666666666666667  0.0000000000000000
1  0.5000000000000000  0.5000000000000000  0.6666666666666667
1  0.5000000000000000  0.3333333333333333  0.8333333333333333
1  0.3333333333333333  0.5000000000000000  0.8333333333333333
1  0.3333333333333333  0.3333333333333333  0.6666666666666667
1  0.6666666666666667  0.0000000000000000  0.3333333333333333
1  0.6666666666666667  0.1666666666666667  0.5000000000000000
1  0.8333333333333333  0.0000000000000000  0.5000000000000000
1  0.8333333333333333  0.1666666666666667  0.3333333333333333
1  0.5000000000000000  0.5000000000000000  0.3333333333333333
1  0.5000000000000000  0.3333333333333333  0.5000000000000000
1  0.3333333333333333  0.5000000000000000  0.5000000000000000
1  0.3333333333333333  0.3333333333333333  0.3333333333333333
1  0.8333333333333333  0.6666666666666667  0.8333333333333333
1  0.5000000000000000  0.3333333333333333  0.1666666666666667
1  0.1666666666666667  0.6666666666666667  0.5000000000000000
1  0.1666666666666667  0.8333333333333333  0.6666666666666667
1  0.0000000000000000  0.6666666666666667  0.3333333333333333
1  0.0000000000000000  0.3333333333333333  0.3333333333333333
1  0.6666666666666667  0.6666666666666667  0.0000000000000000
1  0.6666666666666667  0.8333333333333333  0.1666666666666667
1  0.8333333333333333  0.6666666666666667  0.1666666666666667
1  0.1666666666666667  0.5000000000000000  0.0000000000000000
1  0.1666666666666667  0.3333333333333333  0.1666666666666667
1  0.0000000000000000  0.8333333333333333  0.5000000000000000
1  0.0000000000000000  0.3333333333333333  0.0000000000000000
1  0.8333333333333333  0.8333333333333333  0.0000000000000000
1  0.1666666666666667  0.1666666666666667  0.6666666666666667
1  0.1666666666666667  0.0000000000000000  0.8333333333333333
1  0.0000000000000000  0.1666666666666667  0.8333333333333333
1  0.0000000000000000  0.0000000000000000  0.6666666666666667
1  0.6666666666666667  0.6666666666666667  0.3333333333333333
1  0.6666666666666667  0.8333333333333333  0.5000000000000000
1  0.8333333333333333  0.6666666666666667  0.5000000000000000
1  0.1666666666666667  0.1666666666666667  0.3333333333333333
1  0.1666666666666667  0.0000000000000000  0.5000000000000000
1  0.0000000000000000  0.1666666666666667  0.5000000000000000
1  0.0000000000000000  0.0000000000000000  0.3333333333333333
1  0.8333333333333333  0.8333333333333333  0.3333333333333333
1  0.1666666666666667  0.1666666666666667  0.0000000000000000
1  0.1666666666666667  0.0000000000000000  0.1666666666666667
1  0.0000000000000000  0.1666666666666667  0.1666666666666667
1  0.0000000000000000  0.0000000000000000  0.0000000000000000
1  0.6666666666666667  0.6666666666666667  0.6666666666666667
1  0.6666666666666667  0.8333333333333333  0.8333333333333333
1  0.0000000000000000  0.5000000000000000  0.5000000000000000
1  0.1666666666666667  0.3333333333333333  0.5000000000000000
1  0.0000000000000000  0.5000000000000000  0.1666666666666667
1  0.5000000000000000  0.8333333333333333  0.6666666666666667
1  0.0000000000000000  0.6666666666666667  0.0000000000000000
1  0.1666666666666667  0.5000000000000000  0.3333333333333333
1  0.0000000000000000  0.8333333333333333  0.1666666666666667
1  0.6666666666666667  0.3333333333333333  0.6666666666666667
1  0.1666666666666667  0.6666666666666667  0.1666666666666667
1  0.6666666666666667  0.5000000000000000  0.8333333333333333
1  0.8333333333333333  0.3333333333333333  0.8333333333333333
1  0.1666666666666667  0.5000000000000000  0.6666666666666667
1  0.1666666666666667  0.3333333333333333  0.8333333333333333
1  0.1666666666666667  0.8333333333333333  0.0000000000000000
1  0.0000000000000000  0.5000000000000000  0.8333333333333333
1  0.0000000000000000  0.3333333333333333  0.6666666666666667
1  0.8333333333333333  0.5000000000000000  0.3333333333333333
1  0.8333333333333333  0.5000000000000000  0.6666666666666667
1  0.8333333333333333  0.5000000000000000  0.5000000000000000
2  0.6666666666666667  0.3333333333333333  0.8333333333333333
2  0.6666666666666667  0.0000000000000000  0.1666666666666667
2  0.6666666666666667  0.1666666666666667  0.0000000000000000
2  0.8333333333333333  0.0000000000000000  0.0000000000000000
2  0.8333333333333333  0.1666666666666667  0.1666666666666667
2  0.8333333333333333  0.8333333333333333  0.8333333333333333
2  0.6666666666666667  0.5000000000000000  0.6666666666666667
2  0.6666666666666667  0.6666666666666667  0.8333333333333333
2  0.6666666666666667  0.8333333333333333  0.6666666666666667
2  0.8333333333333333  0.6666666666666667  0.6666666666666667
2  0.8333333333333333  0.3333333333333333  0.3333333333333333
2  0.8333333333333333  0.3333333333333333  0.6666666666666667
2  0.6666666666666667  0.0000000000000000  0.5000000000000000
2  0.6666666666666667  0.3333333333333333  0.1666666666666667
2  0.8333333333333333  0.0000000000000000  0.3333333333333333
2  0.6666666666666667  0.5000000000000000  0.0000000000000000
2  0.8333333333333333  0.8333333333333333  0.1666666666666667
2  0.8333333333333333  0.3333333333333333  0.0000000000000000
2  0.8333333333333333  0.6666666666666667  0.0000000000000000
2  0.6666666666666667  0.8333333333333333  0.0000000000000000
2  0.8333333333333333  0.1666666666666667  0.8333333333333333
2  0.6666666666666667  0.6666666666666667  0.1666666666666667
2  0.8333333333333333  0.5000000000000000  0.1666666666666667
2  0.6666666666666667  0.1666666666666667  0.3333333333333333
2  0.8333333333333333  0.0000000000000000  0.6666666666666667
2  0.6666666666666667  0.0000000000000000  0.8333333333333333
2  0.6666666666666667  0.6666666666666667  0.5000000000000000
2  0.6666666666666667  0.8333333333333333  0.3333333333333333
2  0.8333333333333333  0.6666666666666667  0.3333333333333333
2  0.8333333333333333  0.8333333333333333  0.5000000000000000
2  0.8333333333333333  0.5000000000000000  0.8333333333333333
2  0.6666666666666667  0.5000000000000000  0.3333333333333333
2  0.8333333333333333  0.1666666666666667  0.5000000000000000
2  0.6666666666666667  0.1666666666666667  0.6666666666666667
2  0.6666666666666667  0.3333333333333333  0.5000000000000000
2  0.0000000000000000  0.0000000000000000  0.1666666666666667
2  0.5000000000000000  0.6666666666666667  0.6666666666666667
2  0.1666666666666667  0.5000000000000000  0.5000000000000000
2  0.0000000000000000  0.3333333333333333  0.8333333333333333
2  0.0000000000000000  0.5000000000000000  0.6666666666666667
2  0.1666666666666667  0.3333333333333333  0.6666666666666667
2  0.1666666666666667  0.5000000000000000  0.8333333333333333
2  0.0000000000000000  0.6666666666666667  0.1666666666666667
2  0.1666666666666667  0.3333333333333333  0.3333333333333333
2  0.0000000000000000  0.8333333333333333  0.0000000000000000
2  0.1666666666666667  0.8333333333333333  0.1666666666666667
2  0.0000000000000000  0.6666666666666667  0.5000000000000000
2  0.0000000000000000  0.8333333333333333  0.3333333333333333
2  0.1666666666666667  0.6666666666666667  0.3333333333333333
2  0.1666666666666667  0.8333333333333333  0.5000000000000000
2  0.0000000000000000  0.6666666666666667  0.8333333333333333
2  0.1666666666666667  0.6666666666666667  0.0000000000000000
2  0.0000000000000000  0.8333333333333333  0.6666666666666667
2  0.0000000000000000  0.5000000000000000  0.3333333333333333
2  0.1666666666666667  0.5000000000000000  0.1666666666666667
2  0.0000000000000000  0.1666666666666667  0.0000000000000000
2  0.1666666666666667  0.0000000000000000  0.0000000000000000
2  0.1666666666666667  0.1666666666666667  0.1666666666666667
2  0.0000000000000000  0.0000000000000000  0.5000000000000000
2  0.0000000000000000  0.1666666666666667  0.3333333333333333
2  0.1666666666666667  0.0000000000000000  0.3333333333333333
2  0.0000000000000000  0.3333333333333333  0.5000000000000000
2  0.1666666666666667  0.1666666666666667  0.5000000000000000
2  0.0000000000000000  0.1666666666666667  0.6666666666666667
2  0.1666666666666667  0.0000000000000000  0.6666666666666667
2  0.1666666666666667  0.1666666666666667  0.8333333333333333
2  0.0000000000000000  0.3333333333333333  0.1666666666666667
2  0.0000000000000000  0.5000000000000000  0.0000000000000000
2  0.1666666666666667  0.3333333333333333  0.0000000000000000
2  0.0000000000000000  0.0000000000000000  0.8333333333333333
2  0.5000000000000000  0.8333333333333333  0.8333333333333333
2  0.1666666666666667  0.6666666666666667  0.6666666666666667
2  0.3333333333333333  0.0000000000000000  0.1666666666666667
2  0.3333333333333333  0.3333333333333333  0.8333333333333333
2  0.3333333333333333  0.5000000000000000  0.6666666666666667
2  0.5000000000000000  0.3333333333333333  0.6666666666666667
2  0.5000000000000000  0.5000000000000000  0.8333333333333333
2  0.3333333333333333  0.6666666666666667  0.1666666666666667
2  0.3333333333333333  0.8333333333333333  0.0000000000000000
2  0.5000000000000000  0.3333333333333333  0.3333333333333333
2  0.5000000000000000  0.6666666666666667  0.0000000000000000
2  0.3333333333333333  0.6666666666666667  0.5000000000000000
2  0.3333333333333333  0.8333333333333333  0.3333333333333333
2  0.5000000000000000  0.6666666666666667  0.3333333333333333
2  0.5000000000000000  0.8333333333333333  0.5000000000000000
2  0.3333333333333333  0.6666666666666667  0.8333333333333333
2  0.3333333333333333  0.8333333333333333  0.6666666666666667
2  0.5000000000000000  0.8333333333333333  0.1666666666666667
2  0.1666666666666667  0.8333333333333333  0.8333333333333333
2  0.3333333333333333  0.5000000000000000  0.3333333333333333
2  0.5000000000000000  0.5000000000000000  0.1666666666666667
2  0.3333333333333333  0.1666666666666667  0.0000000000000000
2  0.5000000000000000  0.0000000000000000  0.0000000000000000
2  0.5000000000000000  0.1666666666666667  0.1666666666666667
2  0.3333333333333333  0.0000000000000000  0.5000000000000000
2  0.3333333333333333  0.1666666666666667  0.3333333333333333
2  0.5000000000000000  0.0000000000000000  0.3333333333333333
2  0.3333333333333333  0.3333333333333333  0.5000000000000000
2  0.5000000000000000  0.1666666666666667  0.5000000000000000
2  0.3333333333333333  0.1666666666666667  0.6666666666666667
2  0.5000000000000000  0.0000000000000000  0.6666666666666667
2  0.5000000000000000  0.1666666666666667  0.8333333333333333
2  0.3333333333333333  0.3333333333333333  0.1666666666666667
2  0.3333333333333333  0.5000000000000000  0.0000000000000000
2  0.5000000000000000  0.3333333333333333  0.0000000000000000
2  0.3333333333333333  0.0000000000000000  0.8333333333333333
2  0.5000000000000000  0.5000000000000000  0.5000000000000000
/

&fitting
    NDATA = 4
    DFILE = disp.dat
    FFILE = force.dat
/

```

**Comment by ttadano** [comment]
Your structure seems to be different from the 3x3x3 conventional supercell of the NaCl structure. It has 109 and 107 atoms of type 1 and 2, respectively.
When I used the supercell structure of my own (please see below), there was no problem. 

```
&general
  PREFIX = example
  MODE = suggest
  NAT = 216
  NKD = 2
  KD = A B
  TOLERANCE = 1.e-5
  PRINTSYM = 1
/

&interaction
  NORDER = 1  # 1: harmonic, 2: cubic, ..
/

&cell
    1.8897259890 # factor 
   19.6805377673   0.0000000000   0.0000000000
    0.0000000000  19.6805377673   0.0000000000
    0.0000000000   0.0000000000  19.6805377673 # cell matrix
/

&cutoff 
*-* None
/

&position
  1    0.000000000000000    0.000000000000000    0.000000000000000
  1    0.000000000000000    0.000000000000000    0.333333333333333
  1    0.000000000000000    0.000000000000000    0.666666666666667
  1    0.000000000000000    0.166666666666667    0.166666666666667
  1    0.000000000000000    0.166666666666667    0.500000000000000
  1    0.000000000000000    0.166666666666667    0.833333333333333
  1    0.000000000000000    0.333333333333333    0.000000000000000
  1    0.000000000000000    0.333333333333333    0.333333333333333
  1    0.000000000000000    0.333333333333333    0.666666666666667
  1    0.000000000000000    0.500000000000000    0.166666666666667
  1    0.000000000000000    0.500000000000000    0.500000000000000
  1    0.000000000000000    0.500000000000000    0.833333333333333
  1    0.000000000000000    0.666666666666667    0.000000000000000
  1    0.000000000000000    0.666666666666667    0.333333333333333
  1    0.000000000000000    0.666666666666667    0.666666666666667
  1    0.000000000000000    0.833333333333333    0.166666666666667
  1    0.000000000000000    0.833333333333333    0.500000000000000
  1    0.000000000000000    0.833333333333333    0.833333333333333
  1    0.166666666666667    0.000000000000000    0.166666666666667
  1    0.166666666666667    0.000000000000000    0.500000000000000
  1    0.166666666666667    0.000000000000000    0.833333333333333
  1    0.166666666666667    0.166666666666667    0.000000000000000
  1    0.166666666666667    0.166666666666667    0.333333333333333
  1    0.166666666666667    0.166666666666667    0.666666666666667
  1    0.166666666666667    0.333333333333333    0.166666666666667
  1    0.166666666666667    0.333333333333333    0.500000000000000
  1    0.166666666666667    0.333333333333333    0.833333333333333
  1    0.166666666666667    0.500000000000000    0.000000000000000
  1    0.166666666666667    0.500000000000000    0.333333333333333
  1    0.166666666666667    0.500000000000000    0.666666666666667
  1    0.166666666666667    0.666666666666667    0.166666666666667
  1    0.166666666666667    0.666666666666667    0.500000000000000
  1    0.166666666666667    0.666666666666667    0.833333333333333
  1    0.166666666666667    0.833333333333333    0.000000000000000
  1    0.166666666666667    0.833333333333333    0.333333333333333
  1    0.166666666666667    0.833333333333333    0.666666666666667
  1    0.333333333333333    0.000000000000000    0.000000000000000
  1    0.333333333333333    0.000000000000000    0.333333333333333
  1    0.333333333333333    0.000000000000000    0.666666666666667
  1    0.333333333333333    0.166666666666667    0.166666666666667
  1    0.333333333333333    0.166666666666667    0.500000000000000
  1    0.333333333333333    0.166666666666667    0.833333333333333
  1    0.333333333333333    0.333333333333333    0.000000000000000
  1    0.333333333333333    0.333333333333333    0.333333333333333
  1    0.333333333333333    0.333333333333333    0.666666666666667
  1    0.333333333333333    0.500000000000000    0.166666666666667
  1    0.333333333333333    0.500000000000000    0.500000000000000
  1    0.333333333333333    0.500000000000000    0.833333333333333
  1    0.333333333333333    0.666666666666667    0.000000000000000
  1    0.333333333333333    0.666666666666667    0.333333333333333
  1    0.333333333333333    0.666666666666667    0.666666666666667
  1    0.333333333333333    0.833333333333333    0.166666666666667
  1    0.333333333333333    0.833333333333333    0.500000000000000
  1    0.333333333333333    0.833333333333333    0.833333333333333
  1    0.500000000000000    0.000000000000000    0.166666666666667
  1    0.500000000000000    0.000000000000000    0.500000000000000
  1    0.500000000000000    0.000000000000000    0.833333333333333
  1    0.500000000000000    0.166666666666667    0.000000000000000
  1    0.500000000000000    0.166666666666667    0.333333333333333
  1    0.500000000000000    0.166666666666667    0.666666666666667
  1    0.500000000000000    0.333333333333333    0.166666666666667
  1    0.500000000000000    0.333333333333333    0.500000000000000
  1    0.500000000000000    0.333333333333333    0.833333333333333
  1    0.500000000000000    0.500000000000000    0.000000000000000
  1    0.500000000000000    0.500000000000000    0.333333333333333
  1    0.500000000000000    0.500000000000000    0.666666666666667
  1    0.500000000000000    0.666666666666667    0.166666666666667
  1    0.500000000000000    0.666666666666667    0.500000000000000
  1    0.500000000000000    0.666666666666667    0.833333333333333
  1    0.500000000000000    0.833333333333333    0.000000000000000
  1    0.500000000000000    0.833333333333333    0.333333333333333
  1    0.500000000000000    0.833333333333333    0.666666666666667
  1    0.666666666666667    0.000000000000000    0.000000000000000
  1    0.666666666666667    0.000000000000000    0.333333333333333
  1    0.666666666666667    0.000000000000000    0.666666666666667
  1    0.666666666666667    0.166666666666667    0.166666666666667
  1    0.666666666666667    0.166666666666667    0.500000000000000
  1    0.666666666666667    0.166666666666667    0.833333333333333
  1    0.666666666666667    0.333333333333333    0.000000000000000
  1    0.666666666666667    0.333333333333333    0.333333333333333
  1    0.666666666666667    0.333333333333333    0.666666666666667
  1    0.666666666666667    0.500000000000000    0.166666666666667
  1    0.666666666666667    0.500000000000000    0.500000000000000
  1    0.666666666666667    0.500000000000000    0.833333333333333
  1    0.666666666666667    0.666666666666667    0.000000000000000
  1    0.666666666666667    0.666666666666667    0.333333333333333
  1    0.666666666666667    0.666666666666667    0.666666666666667
  1    0.666666666666667    0.833333333333333    0.166666666666667
  1    0.666666666666667    0.833333333333333    0.500000000000000
  1    0.666666666666667    0.833333333333333    0.833333333333333
  1    0.833333333333333    0.000000000000000    0.166666666666667
  1    0.833333333333333    0.000000000000000    0.500000000000000
  1    0.833333333333333    0.000000000000000    0.833333333333333
  1    0.833333333333333    0.166666666666667    0.000000000000000
  1    0.833333333333333    0.166666666666667    0.333333333333333
  1    0.833333333333333    0.166666666666667    0.666666666666667
  1    0.833333333333333    0.333333333333333    0.166666666666667
  1    0.833333333333333    0.333333333333333    0.500000000000000
  1    0.833333333333333    0.333333333333333    0.833333333333333
  1    0.833333333333333    0.500000000000000    0.000000000000000
  1    0.833333333333333    0.500000000000000    0.333333333333333
  1    0.833333333333333    0.500000000000000    0.666666666666667
  1    0.833333333333333    0.666666666666667    0.166666666666667
  1    0.833333333333333    0.666666666666667    0.500000000000000
  1    0.833333333333333    0.666666666666667    0.833333333333333
  1    0.833333333333333    0.833333333333333    0.000000000000000
  1    0.833333333333333    0.833333333333333    0.333333333333333
  1    0.833333333333333    0.833333333333333    0.666666666666667
  2    0.000000000000000    0.000000000000000    0.166666666666667
  2    0.000000000000000    0.000000000000000    0.500000000000000
  2    0.000000000000000    0.000000000000000    0.833333333333333
  2    0.000000000000000    0.166666666666667    0.000000000000000
  2    0.000000000000000    0.166666666666667    0.333333333333333
  2    0.000000000000000    0.166666666666667    0.666666666666667
  2    0.000000000000000    0.333333333333333    0.166666666666667
  2    0.000000000000000    0.333333333333333    0.500000000000000
  2    0.000000000000000    0.333333333333333    0.833333333333333
  2    0.000000000000000    0.500000000000000    0.000000000000000
  2    0.000000000000000    0.500000000000000    0.333333333333333
  2    0.000000000000000    0.500000000000000    0.666666666666667
  2    0.000000000000000    0.666666666666667    0.166666666666667
  2    0.000000000000000    0.666666666666667    0.500000000000000
  2    0.000000000000000    0.666666666666667    0.833333333333333
  2    0.000000000000000    0.833333333333333    0.000000000000000
  2    0.000000000000000    0.833333333333333    0.333333333333333
  2    0.000000000000000    0.833333333333333    0.666666666666667
  2    0.166666666666667    0.000000000000000    0.000000000000000
  2    0.166666666666667    0.000000000000000    0.333333333333333
  2    0.166666666666667    0.000000000000000    0.666666666666667
  2    0.166666666666667    0.166666666666667    0.166666666666667
  2    0.166666666666667    0.166666666666667    0.500000000000000
  2    0.166666666666667    0.166666666666667    0.833333333333333
  2    0.166666666666667    0.333333333333333    0.000000000000000
  2    0.166666666666667    0.333333333333333    0.333333333333333
  2    0.166666666666667    0.333333333333333    0.666666666666667
  2    0.166666666666667    0.500000000000000    0.166666666666667
  2    0.166666666666667    0.500000000000000    0.500000000000000
  2    0.166666666666667    0.500000000000000    0.833333333333333
  2    0.166666666666667    0.666666666666667    0.000000000000000
  2    0.166666666666667    0.666666666666667    0.333333333333333
  2    0.166666666666667    0.666666666666667    0.666666666666667
  2    0.166666666666667    0.833333333333333    0.166666666666667
  2    0.166666666666667    0.833333333333333    0.500000000000000
  2    0.166666666666667    0.833333333333333    0.833333333333333
  2    0.333333333333333    0.000000000000000    0.166666666666667
  2    0.333333333333333    0.000000000000000    0.500000000000000
  2    0.333333333333333    0.000000000000000    0.833333333333333
  2    0.333333333333333    0.166666666666667    0.000000000000000
  2    0.333333333333333    0.166666666666667    0.333333333333333
  2    0.333333333333333    0.166666666666667    0.666666666666667
  2    0.333333333333333    0.333333333333333    0.166666666666667
  2    0.333333333333333    0.333333333333333    0.500000000000000
  2    0.333333333333333    0.333333333333333    0.833333333333333
  2    0.333333333333333    0.500000000000000    0.000000000000000
  2    0.333333333333333    0.500000000000000    0.333333333333333
  2    0.333333333333333    0.500000000000000    0.666666666666667
  2    0.333333333333333    0.666666666666667    0.166666666666667
  2    0.333333333333333    0.666666666666667    0.500000000000000
  2    0.333333333333333    0.666666666666667    0.833333333333333
  2    0.333333333333333    0.833333333333333    0.000000000000000
  2    0.333333333333333    0.833333333333333    0.333333333333333
  2    0.333333333333333    0.833333333333333    0.666666666666667
  2    0.500000000000000    0.000000000000000    0.000000000000000
  2    0.500000000000000    0.000000000000000    0.333333333333333
  2    0.500000000000000    0.000000000000000    0.666666666666667
  2    0.500000000000000    0.166666666666667    0.166666666666667
  2    0.500000000000000    0.166666666666667    0.500000000000000
  2    0.500000000000000    0.166666666666667    0.833333333333333
  2    0.500000000000000    0.333333333333333    0.000000000000000
  2    0.500000000000000    0.333333333333333    0.333333333333333
  2    0.500000000000000    0.333333333333333    0.666666666666667
  2    0.500000000000000    0.500000000000000    0.166666666666667
  2    0.500000000000000    0.500000000000000    0.500000000000000
  2    0.500000000000000    0.500000000000000    0.833333333333333
  2    0.500000000000000    0.666666666666667    0.000000000000000
  2    0.500000000000000    0.666666666666667    0.333333333333333
  2    0.500000000000000    0.666666666666667    0.666666666666667
  2    0.500000000000000    0.833333333333333    0.166666666666667
  2    0.500000000000000    0.833333333333333    0.500000000000000
  2    0.500000000000000    0.833333333333333    0.833333333333333
  2    0.666666666666667    0.000000000000000    0.166666666666667
  2    0.666666666666667    0.000000000000000    0.500000000000000
  2    0.666666666666667    0.000000000000000    0.833333333333333
  2    0.666666666666667    0.166666666666667    0.000000000000000
  2    0.666666666666667    0.166666666666667    0.333333333333333
  2    0.666666666666667    0.166666666666667    0.666666666666667
  2    0.666666666666667    0.333333333333333    0.166666666666667
  2    0.666666666666667    0.333333333333333    0.500000000000000
  2    0.666666666666667    0.333333333333333    0.833333333333333
  2    0.666666666666667    0.500000000000000    0.000000000000000
  2    0.666666666666667    0.500000000000000    0.333333333333333
  2    0.666666666666667    0.500000000000000    0.666666666666667
  2    0.666666666666667    0.666666666666667    0.166666666666667
  2    0.666666666666667    0.666666666666667    0.500000000000000
  2    0.666666666666667    0.666666666666667    0.833333333333333
  2    0.666666666666667    0.833333333333333    0.000000000000000
  2    0.666666666666667    0.833333333333333    0.333333333333333
  2    0.666666666666667    0.833333333333333    0.666666666666667
  2    0.833333333333333    0.000000000000000    0.000000000000000
  2    0.833333333333333    0.000000000000000    0.333333333333333
  2    0.833333333333333    0.000000000000000    0.666666666666667
  2    0.833333333333333    0.166666666666667    0.166666666666667
  2    0.833333333333333    0.166666666666667    0.500000000000000
  2    0.833333333333333    0.166666666666667    0.833333333333333
  2    0.833333333333333    0.333333333333333    0.000000000000000
  2    0.833333333333333    0.333333333333333    0.333333333333333
  2    0.833333333333333    0.333333333333333    0.666666666666667
  2    0.833333333333333    0.500000000000000    0.166666666666667
  2    0.833333333333333    0.500000000000000    0.500000000000000
  2    0.833333333333333    0.500000000000000    0.833333333333333
  2    0.833333333333333    0.666666666666667    0.000000000000000
  2    0.833333333333333    0.666666666666667    0.333333333333333
  2    0.833333333333333    0.666666666666667    0.666666666666667
  2    0.833333333333333    0.833333333333333    0.166666666666667
  2    0.833333333333333    0.833333333333333    0.500000000000000
  2    0.833333333333333    0.833333333333333    0.833333333333333
/

```

**Comment by jochym** [comment]
Dear @ttadano ! Thank you so much for your help. "To err is a human" but to really mess up with things you need computers ;) Indeed we have made a mistake generating the supercell. Sorry for taking up your valuable time. I'm closing this now.
